name: Daily Commit

on:
  schedule:
    # Runs every day at 18:15 UTC (23:45 IST)
    - cron: '15 18 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Required to push commits using GITHUB_TOKEN

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Required: include your email in step name
      - name: Commit step owned by 25ds1000231@ds.study.iitm.ac.in
        run: echo "Email step verification success"

      # Make a change so there’s always something to commit
      - name: Make a change for today
        run: |
          echo "Daily heartbeat at $(date -u +'%Y-%m-%d %H:%M:%S') UTC" >> .daily_heartbeat.log

      # Commit and push
      - name: Commit and push the change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .daily_heartbeat.log
          git commit -m "chore: daily commit at $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push
